### PR TITLE
Kyouka fix. Add/remove something from index.html

### PR DESCRIPTION
**Pull request by hngtuong**
Add Timestamp and remove some dead/outdated links.
I'll let Blead merge this.

### CODE REVIEW

**Comment by blead** [comment]
Do you intend to change the entry every update? That sounds like an exhaustive work in my opinion.

**Comment by hngtuong** [comment]
Not really. They are hardtypo.
Should I put in title tag instead?

**Comment by blead** [comment]
We actually already have something like that implemented.
I hid it together with the Kyubey image some time ago.

https://github.com/blead/cosmiccalc/blob/a94f0d6e0a81d6b7f6e797124c6c424281d2e182/index.html#L98

During startup, it will insert the string from here:

https://github.com/blead/cosmiccalc/blob/591b0fa576e54e6c64d4b526b7aa3e7b11f27429/js/cosmicalc.js#L28

**Comment by hngtuong** [comment]
I don't see any difference between put in html and js file.
Also I don't want to touch the coding part unless I have to.
Still have something to improve tho.

**Comment by blead** [comment]
Well, I'm just letting you know that it is already there if you want to utilize it.

`<a>` is not a good tag semantically. To maintain the styling, we might need some small changes in the css file. Then maybe we can put something like `<span class="link">` in there.

That's pretty simple though so feel free to pick the choice you prefer. I can help with the implementation.

**Comment by hngtuong** [comment]
Your pick.
More simpler more better.

**Comment by blead** [comment]
Well the one with the least work is what I mentioned.

Uncomment this line:
https://github.com/blead/cosmiccalc/blob/a94f0d6e0a81d6b7f6e797124c6c424281d2e182/index.html#L98

After that, simply edit this line every time we want to update the number:
https://github.com/blead/cosmiccalc/blob/591b0fa576e54e6c64d4b526b7aa3e7b11f27429/js/cosmicalc.js#L28

Don't worry about touching the scripts, editing that particular line will not break anything.

I have an idea of automating this. Maybe I can put up something cool in the future.

**Comment by hngtuong** [comment]
Ok. Push them in appspot for me.
Thanks.

**Pull request merged**
